=== RenataYermak/epam-training-project5-parsers/src/main/resources/cardList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns ="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/cards"
        xmlns:tns="http://www.example.com/cards"
        elementFormDefault="qualified">

    <element name="cards">
        <complexType>
            <sequence>
                <element name="Card"  type="tns:Card" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Card">
        <sequence>
            <element name="Id" type="long"/>
            <element name="Theme" type="tns:Theme"/>
            <element name="Type" type="tns:Type"/>
            <element name="Country" type="string"/>
            <element name="Year" type="date"/>
            <element name="Author" type="string"/>
            <element name="Valuable" type="tns:Valuable"/>
        </sequence>
    </complexType>
    <simpleType name="Theme">
        <restriction base="string">
            <enumeration value="Cityscape"/>
            <enumeration value="Nature"/>
            <enumeration value="People"/>
            <enumeration value="Religion"/>
            <enumeration value="Sport"/>
            <enumeration value="Architecture"/>
        </restriction>
    </simpleType>
    <simpleType name="Type">
        <restriction base="string">
            <enumeration value="Congratulatory"/>
            <enumeration value="Advertising"/>
            <enumeration value="Usual"/>
        </restriction>
    </simpleType>
    <simpleType name="Valuable">
        <restriction base="string">
            <enumeration value="Historical"/>
            <enumeration value="Collectible"/>
            <enumeration value="Thematic"/>
        </restriction>
    </simpleType>
</schema>

=== RenataYermak/epam-training-project5-parsers/src/main/resources/cardList.xml
<?xml version="1.0" encoding="UTF-8"?>
<cards xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.example.com/cards"
       xsi:schemaLocation="http://www.example.com/cards cardList.xsd">

    <Card>
        <Id>1</Id>
        <Theme>Cityscape</Theme>
        <Type>Advertising</Type>
        <Country>USA</Country>
        <Year>1997-12-12</Year>
        <Author>Someone</Author>
        <Valuable>Collectible</Valuable>
    </Card>
    <Card>
        <Id>2</Id>
        <Theme>Nature</Theme>
        <Type>Advertising</Type>
        <Country>Canada</Country>
        <Year>1963-10-26</Year>
        <Author>Someone</Author>
        <Valuable>Historical</Valuable>
    </Card>
    <Card>
        <Id>3</Id>
        <Theme>People</Theme>
        <Type>Usual</Type>
        <Country>Great Britain</Country>
        <Year>1977-06-08</Year>
        <Author>Author</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>4</Id>
        <Theme>Sport</Theme>
        <Type>Congratulatory</Type>
        <Country>Brazil</Country>
        <Year>2000-04-30</Year>
        <Author>Someone</Author>
        <Valuable>Collectible</Valuable>
    </Card>
    <Card>
        <Id>5</Id>
        <Theme>Sport</Theme>
        <Type>Advertising</Type>
        <Country>Canada</Country>
        <Year>2003-01-01</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>6</Id>
        <Theme>Nature</Theme>
        <Type>Usual</Type>
        <Country>USA</Country>
        <Year>1877-12-13</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>7</Id>
        <Theme>Religion</Theme>
        <Type>Congratulatory</Type>
        <Country>India</Country>
        <Year>2009-10-24</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>8</Id>
        <Theme>Cityscape</Theme>
        <Type>Advertising</Type>
        <Country>Canada</Country>
        <Year>1997-03-30</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>9</Id>
        <Theme>People</Theme>
        <Type>Usual</Type>
        <Country>Brazil</Country>
        <Year>1908-12-17</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>10</Id>
        <Theme>Sport</Theme>
        <Type>Advertising</Type>
        <Country>Italy</Country>
        <Year>2012-12-19</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>11</Id>
        <Theme>Architecture</Theme>
        <Type>Congratulatory</Type>
        <Country>Belarus</Country>
        <Year>2019-11-26</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>12</Id>
        <Theme>Nature</Theme>
        <Type>Advertising</Type>
        <Country>Canada</Country>
        <Year>1998-10-29</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>13</Id>
        <Theme>Sport</Theme>
        <Type>Usual</Type>
        <Country>USA</Country>
        <Year>1989-05-18</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>14</Id>
        <Theme>Cityscape</Theme>
        <Type>Usual</Type>
        <Country>Russia</Country>
        <Year>2013-07-28</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>15</Id>
        <Theme>Sport</Theme>
        <Type>Advertising</Type>
        <Country>Canada</Country>
        <Year>2007-09-04</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card>
        <Id>16</Id>
        <Theme>Religion</Theme>
        <Type>Congratulatory</Type>
        <Country>Belarus</Country>
        <Year>1898-02-01</Year>
        <Author>Someone</Author>
        <Valuable>Thematic</Valuable>
    </Card>
</cards>
